# http://www-stat.stanford.edu/~tibs/superpc/tutorial.html
library(superpc)
exprs<-as.matrix(read.table("data_raw.txt",header=T,sep='\t',row.names=1, as.is=T))
y<-c(rep(0,22),rep(1,16))
data<-list(x=exprs,y=y,featurenames=rownames(exprs))
train.obj<- superpc.train(data, type="regression")
cv.obj<-superpc.cv(train.obj, data)
superpc.plotcv(cv.obj)
lrtest.obj<-superpc.lrtest.curv(train.obj, data,data)
superpc.plot.lrtest(lrtest.obj)
fit.cts<- superpc.predict(train.obj, data, data, threshold=1.1, n.components=3, prediction.type="discrete")
superpc.fit.to.outcome(train.obj, data, fit.cts$v.pred)
fit.groups<- superpc.predict(train.obj, data, data, threshold=1.1, n.components=1, prediction.type="discrete")
superpc.fit.to.outcome(train.obj, data, fit.groups$v.pred)
# plot(survfit(Surv(data$y,data$censoring.status)~fit.groups$v.pred), col=2:3, xlab="time", ylab="Prob survival")
fit.red<- superpc.predict.red(train.obj, data, data, threshold=1.1)
fit.redcv<- superpc.predict.red.cv(fit.red, cv.obj,  data,  threshold=1.1)
superpc.plotred.lrtest(fit.redcv)
superpc.listfeatures(data, train.obj, fit.red)